# Generated by Django 3.1 on 2020-08-12 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField(max_length=256)),
                ('image', models.ImageField(upload_to='movies')),
                ('category', models.CharField(choices=[('A', 'Action'), ('D', 'Drama'), ('C', 'Comedy'), ('R', 'Romance'), ('F', 'Ficcion')], max_length=1)),
                ('language', models.CharField(choices=[('EN', 'English'), ('ES', 'Spanish'), ('GR', 'Germany')], max_length=2)),
                ('status', models.CharField(choices=[('RA', 'Recently Added'), ('MW', 'Most Wachet'), ('TR', 'Top Rated')], max_length=2)),
                ('year', models.DateField()),
                ('views_count', models.IntegerField(default=0)),
            ],
        ),
    ]
